kind: pipeline
type: docker
name: default

steps:
- name: install_dependencies
  image: node:14
  commands:
  - npm install

- name: test
  image: node:14
  commands:
  - npm test

- name: build
  image: plugins/docker
  settings:
    repo: your-docker-repo/myapp
    tags:
      - ${DRONE_COMMIT_SHA}
    registry: docker.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: deploy
  image: alpine/helm:3.5.4
  environment:
    KUBERNETES_SERVICE_HOST:
      from_secret: kubernetes_service_host
    KUBERNETES_SERVICE_PORT:
      from_secret: kubernetes_service_port
    KUBERNETES_TOKEN:
      from_secret: kubernetes_token
  commands:
  - helm upgrade --install myapp ./helm --set image.repository=your-docker-repo/myapp --set image.tag=${DRONE_COMMIT_SHA}

