kind: pipeline
type: kubernetes
name: default

trigger:
  event:
  - push
  branch:
  - master

steps:
- name: install_dependencies
  image: node:14
  commands:
  - npm install

- name: debug
  image: node:14
  commands:
  - cat package.json
  - ls -la
  - ls -la src
  - ls -la test

- name: test
  image: node:14
  commands:
  - npm test

- name: build
  image: plugins/docker
  settings:
    repo: thapapath/myapp2
    tags:
      - ${DRONE_COMMIT_SHA}
    registry: docker.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: deploy
  image:

- name: cache-reset
  image: alpine
  commands:
  - rm -rf /drone/src/*