namespace: my-app-namespace
replicaCount: 1
image:
  repository: thapapath/myapp2
  tag: latest
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1000m"